### ISSUE TITLE
細かい修正

### ISSUE THREAD

**Issue by h-otter** [UEC-VBSeminar/Helper2.h#43]
- [x] update README.md
- [x] LEDの無駄なタブを変更

**Comment by h-otter** [comment]
- [ ] stepcolor keywords.txt 登録

**Comment by h-otter** [comment]
- [ ] 資料 step削除
- [ ] 関数命名規則

**Comment by kyontan** [comment]
資料 step削除 とは?

**Comment by h-otter** [comment]
引数にstepって書いてあったから省略できないと勘違いして、変な値を代入する人が多かったから

配られたプリントの話

**Comment by kyontan** [comment]
なるほど、じゃあこのリポジトリ上のコードには関係なさそうですね。
