### ISSUE TITLE
Remove external libraries from this repository

### ISSUE THREAD

**Issue by kyontan** [UEC-VBSeminar/Helper2.h#48]
ADXL345, Adafruit_NeoPixel を外部から参照するようにしましょう!

- [x] ADXL345.h, ADXL345.cpp の削除
- [x] Adafruit_NeoPixel.h, Adafruit_NeoPixel.cpp の削除
- [x] CI が通るようにする 
- [x] LICENSE を MIT License に変更する
- [x] Authors の欄を README.md に追加する

参考:
https://github.com/kyontan/adxl345driver
https://github.com/adafruit/Adafruit_NeoPixel

( これが使えるなら使ったほうが信頼性的に嬉しそうですね(実機検証必須) https://github.com/adafruit/Adafruit_ADXL345 )

**Comment by h-otter** [comment]
closeしていいんじゃないんですかね

**Comment by kyontan** [comment]
Closed by #50
