### ISSUE TITLE
Accel class : コメントのミス

### ISSUE THREAD

**Issue by skishida** [UEC-VBSeminar/Helper2.h#51]
https://github.com/UEC-VBSeminar/Helper2.h/blob/master/Accel.cpp#L189-L191

実装は フレーム ではなく ms 

デバッグ的にはここの実装もフレーム単位のほうが多少楽な気がするけど
汎用性を考えるとmsのほうがいいのでしょう

**Comment by kyontan** [comment]
これはコメントの誤りですね。
修正します
